### ISSUE TITLE
No function

### ISSUE THREAD

**Issue by Fuxifux** [J0EK3R/fhem-grohe-ondus#1]
Since laster Serverworks from Grohe,the Module from Fhem dos not work anymore.

**Comment by J0EK3R** [comment]
...can't find the problem. :(
So I did a bad login fix. Perhaps it works now...

**Comment by Fuxifux** [comment]
It works. Perfect.Thanks !!!!!!

**Comment by J0EK3R** [comment]
No, it doesn‘t.... :/

**Comment by Fuxifux** [comment]
You are right,it doesn't

**Comment by J0EK3R** [comment]
I've made another "bad fix" with a complete login each time the data is polled...
I need to rework that mess...

**Comment by Fuxifux** [comment]
Thank you very much !!

**Comment by Fuxifux** [comment]
The Connection is OK for a few days,then i must manually set get token,then its OK.

**Comment by J0EK3R** [comment]
Yes, I know.
Be patient: currently I‘m rewriting the complete module.
This module was my first attempt in perl - did I mention that I don‘t like perl?! ;)

**Comment by Fuxifux** [comment]
I have any idea or experience in programming. I understand you 😁

**Comment by J0EK3R** [comment]
I completely reworked the modules: V3.0.0 is available.
Hope that mess works now...
