### ISSUE TITLE
Update Status

### ISSUE THREAD

**Issue by DeepflashX** [J0EK3R/fhem-grohe-ondus#3]
Hi J0EK3R,

kannst du mir sagen, wo ich die aktuell verwendete Version in FHEM sehen kann?
Irgendwie aktualisieren sich die Daten bei mir seit Ende September nicht mehr.
Habe bereits ein "update" durchgeführt und ein update add auch nochmal, aber geändert hat sich da nichts.
Ein update list sagt mir, dass gerade ein Update durchgeführt wird.

Davon abgesehen: Ich habe die Vermutung, dass hansgrohe mit dem Sodabase / Aqittura System ein gleiches Interface nutzt, wie Grohe. 
Wie komm ich denn auf die API-Links, müsste ich dazu in den Quellcode der App schauen?

**Comment by J0EK3R** [comment]
Moin DeepflashX,

die aktuelle Modul-Version steht in den Internals.
Momentan ist das die 5.0.4.

Dass die Daten nicht aktualisiert werden, ist seltsam - bei mir geht's.
Siehe auch die letzten Beiträge im [Fhem-Forum zu Grohe](https://forum.fhem.de/index.php?topic=80754.0).
Ich müsste aber sowieso komplett überarbeiten...

Zum Thema "hansgrohe" kann ich nur wenig sagen - ich hab damals bestehenden Code genommen und versucht, das in Perl für FHEM umzustricken...

Aber das wäre mein Ansatz - ohne wirklich viel Erfahrung damit zu haben:
Die APK der Android-App mit einem geeigneten Tool untersuchen.
Bei den Strings müssten dann die API-Endpunkte zu finden sein.

Oder, ein noch besserer Ansatz: gibt's vielleicht schon was auf GitHub...?!?

Leider habe ich momentan keine Zeit (-> Baby) und kann nicht supporten...
